name: Maven

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run:
          mvn -Dtest="com.example.demo.UnitTests.GradingTasksUnitTets.GraderToGradingTaskUnitTests","com.example.demo.UnitTests.GradingTasksUnitTets.GraderToParticipantUnitTests","com.example.demo.UnitTests.GradingTasksUnitTets.GradingTaskUnitTests","com.example.demo.UnitTests.ResultsUnitTests.AnswerUnitTests","com.example.demo.UnitTests.ResultsUnitTests.CodeResultUnitTests","com.example.demo.UnitTests.ResultsUnitTests.QuestionnaireResultUnitTests","com.example.demo.UnitTests.ResultsUnitTests.TaggingResultUnitTests","com.example.demo.UnitTests.ResultsUnitTests.TagUnitTests","com.example.demo.UnitTests.StagesUnitTests.CodeUnitTest","com.example.demo.UnitTests.StagesUnitTests.InfoStageTest","com.example.demo.UnitTests.StagesUnitTests.QuestionnaireUnitTest","com.example.demo.UnitTests.StagesUnitTests.QuestionUnitTests","com.example.demo.UnitTests.StagesUnitTests.RequirementTest","com.example.demo.UnitTests.StagesUnitTests.StageUnitTest","com.example.demo.UnitTests.StagesUnitTests.TaggingStageTest","com.example.demo.UnitTests.UsersUnitTests.ExperimenteeUnitTest","com.example.demo.UnitTests.UsersUnitTests.GraderUnitTest","com.example.demo.UnitTests.UsersUnitTests.ManagementUserTest","com.example.demo.UnitTests.UsersUnitTests.ParticipantTest","com.example.demo.UnitTests.ExperimentUnitTest","com.example.demo.UnitTests.ManagementUserToExperimentUnitTest","com.example.demo.UnitTests.PermissionUnitTest" test