name: Maven

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: |
          mvn -Dtest="com.example.demo.UnitTests.GradingTasksUnitTets.*" test
#          mvn -Dtest="com.example.demo.UnitTests.GradingTasksUnitTets.GraderToParticipantUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.GradingTasksUnitTets.GradingTaskUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.ResultsUnitTests.AnswerUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.ResultsUnitTests.CodeResultUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.ResultsUnitTests.QuestionnaireResultUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.ResultsUnitTests.TaggingResultUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.ResultsUnitTests.TagUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.StagesUnitTests.CodeUnitTest" test
#          mvn -Dtest="com.example.demo.UnitTests.StagesUnitTests.InfoStageTest" test
#          mvn -Dtest="com.example.demo.UnitTests.StagesUnitTests.QuestionnaireUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.StagesUnitTests.QuestionUnitTests" test
#          mvn -Dtest="com.example.demo.UnitTests.StagesUnitTests.RequirementTest" test
#          mvn -Dtest="com.example.demo.UnitTests.StagesUnitTests.StageUnitTest" test
#          mvn -Dtest="com.example.demo.UnitTests.StagesUnitTests.TaggingStageTest" test
#          mvn -Dtest="com.example.demo.UnitTests.UsersUnitTests.ExperimenteeUnitTest" test
#          mvn -Dtest="com.example.demo.UnitTests.UsersUnitTests.GraderUnitTest" test
#          mvn -Dtest="com.example.demo.UnitTests.UsersUnitTests.ManagementUserTest" test
#          mvn -Dtest="com.example.demo.UnitTests.UsersUnitTests.ParticipantTest" test
#          mvn -Dtest="com.example.demo.UnitTests.ExperimentUnitTest" test
#          mvn -Dtest="com.example.demo.UnitTests.ManagementUserToExperimentUnitTest" test
#          mvn -Dtest="com.example.demo.UnitTests.PermissionUnitTest" test